baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
enableEmoji = true
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
        
[markup.goldmark.renderer]
  unsafe = true

[menus]
  [[menus.header]]
    name = 'Accueil'
    url = '/'
    weight = 1
  [[menus.header]]
    name = 'Projets'
    url = '/projets'
    weight = 2
  [[menus.header]]
    name = 'Lab'
    url = '/lab'
    weight = 3
  [[menus.header]]
    name = 'Contact'
    url = '/contact'
    weight = 20