baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
enableEmoji = true
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true